public enum WinCondtion 
{
    TOP_HORIZONTAL,
    MIDDLE_HORIZONTAL,
    BOTTOM_HORIZONTAL,
    LEFT_VERTICAL,
    MIDDLE_VERTICAL,
    RIGHT_VERTICAL,
    TOP_LEFT_TO_BOTTOM_RIGHT,
    TOP_RIGHT_TO_BOTTOM_LEFT;

    
}
